joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P14, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("E")
    basic.pause(100)
    basic.clearScreen()
    radio.sendValue("Back", 1)
})
joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P15, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("F")
    basic.pause(100)
    basic.clearScreen()
    radio.sendValue("Rigth", 1)
})
joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P13, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("D")
    basic.pause(100)
    basic.clearScreen()
    radio.sendValue("Front", 1)
})
joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P12, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("C")
    basic.pause(100)
    basic.clearScreen()
    radio.sendValue("Left", 1)
})
joystickbit.initJoystickBit()
joystickbit.Vibration_Motor(100)
radio.setGroup(7)
radio.sendNumber(7)
basic.forever(function () {
    basic.showString("" + (joystickbit.getRockerValue(joystickbit.rockerType.X)))
    basic.pause(100)
    basic.showString("" + (joystickbit.getRockerValue(joystickbit.rockerType.Y)))
    basic.pause(100)
    radio.sendValue("X", joystickbit.getRockerValue(joystickbit.rockerType.X))
    radio.sendValue("Y", joystickbit.getRockerValue(joystickbit.rockerType.Y))
})
