joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P14, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("E")
    basic.pause(100)
    basic.clearScreen()
})
joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P15, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("F")
    basic.pause(100)
    basic.clearScreen()
})
joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P13, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("D")
    basic.pause(100)
    basic.clearScreen()
})
joystickbit.onButtonEvent(joystickbit.JoystickBitPin.P12, joystickbit.ButtonType.down, function () {
    joystickbit.Vibration_Motor(100)
    basic.showString("C")
    basic.pause(100)
    basic.clearScreen()
    radio.sendValue("C", 1)
    basic.pause(500)
    radio.sendValue("C", 0)
})
joystickbit.initJoystickBit()
joystickbit.Vibration_Motor(100)
radio.setGroup(7)
radio.sendNumber(7)
basic.forever(function () {
    radio.sendValue("X", joystickbit.getRockerValue(joystickbit.rockerType.X))
    radio.sendValue("Y", joystickbit.getRockerValue(joystickbit.rockerType.Y))
})
